name: 'G& C Love Group, 925-926'
favicon: null
layout_spectrum: 0.7375266870949417
typography_spectrum: 0.4852460543625057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.16575856995768845
  lightness: 0.7182616114150733
  saturation: 0.029266899917274714
  rhythmicContrast: 0.8700396453496069
purpose: []
